apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplebank
  namespace: samplebank
spec:
  selector:
    matchLabels:
      app: samplebank
  replicas: 1
  template:
    metadata:
      labels:
        app: samplebank
    spec:
      containers:
      - name: samplebank
        image: sercanyz/samplebank:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: samplebank
  namespace: samplebank
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app:  samplebank
  type: NodePort